DEV: update ioto

diff --git a/ioto/Makefile b/ioto/Makefile
--- a/ioto/Makefile
+++ b/ioto/Makefile
@@ -2,49 +2,32 @@
 #   Makefile - Top-level Ioto makefile
 #
 #	This Makefile is used for native builds and for ESP32 configuration.
+#	It is a wrapper over generated makefiles under ./projects.
 #
 #	Use "make help" for a list of available make variable options.
 #
-#	Note: In this Makefile and projects/*.mk, the PROFILE is set to "default"
-#	OPTIMIZE is set to debug or release.
-#
 
 SHELL		:= /bin/bash
-TOOLS		:= $(shell bin/prep-build)
-NAME		:= ioto
-PROFILE 	:= dev
+PROFILE 	?= dev
+OPTIMIZE	?= debug
+TOOLS	    := $(shell bin/prep-build)
 TOP			:= $(shell realpath .)
-BASE		:= $(shell realpath .)
-STATE		:= $(TOP)/state
-CONFIG		:= $(STATE)/config
-DB			:= $(STATE)/db
-CERTS 		:= $(STATE)/certs
-SITE		:= $(STATE)/site
-BUILD		:= build
-BIN			:= $(BASE)/$(BUILD)/bin
-PATH		:= $(BASE)/bin:$(BIN):$(PATH)
-CDPATH		:=
-OS			:= $(shell uname | sed 's/CYGWIN.*/windows/;s/Darwin/macosx/' | tr '[A-Z]' '[a-z]')
-VERSION		:= $(shell ./bin/json version pak.json)
-OPTIMIZE	:= $(shell ./bin/json -n --profile $(PROFILE) --default debug optimize $(CONFIG)/ioto.json5)
-APP			:= $(shell ./bin/json -n --default demo app $(CONFIG)/ioto.json5)
-LAPP		:= $(shell echo $(APP) | tr a-z A-Z)
+APP			?= $(shell if [ -f build/.app ] ; then cat build/.app ; else echo unit ; fi)
 MAKE		:= $(shell if which gmake >/dev/null 2>&1; then echo gmake ; else echo make ; fi) --no-print-directory
-PROJECT		:= projects/$(NAME)-$(OS)-default.mk
+OS			:= $(shell uname | sed 's/CYGWIN.*/windows/;s/Darwin/macosx/' | tr '[A-Z]' '[a-z]')
+ARCH		?= $(shell uname -m | sed 's/i.86/x86/;s/x86_64/x64/;s/mips.*/mips/;s/aarch/arm/')
+LOCAL 		:= $(strip $(wildcard ./.local.mk))
+PROJECT		:= projects/ioto-$(OS)-default.mk
+CONFIG		:= $(TOP)/state/config
+BUILD		:= build
 
-ifeq ($(ARCH),)
-	ARCH	:= $(shell uname -m | sed 's/i.86/x86/;s/x86_64/x64/;s/mips.*/mips/;s/aarch/arm/')
-endif
-
-#
-#	Dynamically create the build control environment from ioto.json5
-#
-ENV			:= $(shell ./bin/json -q --env services $(CONFIG)/ioto.json5 >.env)
-
-include		.env
+BIN			:= $(TOP)/$(BUILD)/bin
+PATH		:= $(TOP)/bin:$(BIN):$(PATH)
+CDPATH		:=
 
 .EXPORT_ALL_VARIABLES:
-.PHONY:		app build certs clean compile compile-app compile-agent config prep profile info show
+
+.PHONY:		app build clean compile config doc info projects show test
 
 ifndef SHOW
 .SILENT:
@@ -52,93 +35,64 @@ endif
 
 all: build
 
-build: prep config compile certs info
+build: config compile info
 
-#
-#	Prepare to build natively using the O/S host platform
-#
-prep:
-	@if [ ! -d "include" -a ! -f ".local.mk" ] ; then \
-		echo ; echo "Ioto has not been correctly installed to use this Makefile" ; echo ; \
-		exit 255 ; \
-	fi
-	mkdir -p $(CONFIG) $(SITE) $(DB) $(CERTS)
-	@if [ "$(APP)" = "blank" ] ; then \
-		echo "      [Info] Building Ioto $(VERSION) optimized for \"$(OPTIMIZE)\"" ; \
-	else \
-		echo "      [Info] Building Ioto $(VERSION) optimized for \"$(OPTIMIZE)\" with the \"$(APP)\" app" ; \
-	fi
-
-#
-#	Configure the selected app
-#
-config: config-app include/ioto-config.h certs/test.crt
-
-config-app:
-	@if [ -f "$(BUILD)/.app" ] ; then \
-		if [ "$(APP)" != "`cat $(BUILD)/.app`" ] ; then \
-			echo "   [Warning] Selected App has changed since the last build." ; \
-			echo "  [Selected] Selected App \"$(APP)\"." ; \
+config:
+	@mkdir -p $(BUILD)/bin $(CONFIG)/certs $(CONFIG)/db $(CONFIG)/site 
+	if [ ! -d apps/$(APP) ] ; then \
+		echo "      [Error] Unknown app \"$(APP)\"" ; exit 255 ; \
+	fi ; \
+	if [ -f build/.app ] ; then \
+		if [ "$(APP)" != "`cat build/.app`" ] ; then \
+			echo "      [Clean] Previous app build" ; \
 			$(MAKE) clean ; \
-			rm -fr $(SITE)/* $(DB)/*.jnl $(DB)/*.db ; \
-			find $(CONFIG) -type f -print | egrep -v 'ioto.json5|device.json5|local.json5' | xargs -r rm ; \
 		fi ; \
-	fi
-	@mkdir -p $(BUILD) ; echo "$(APP)" >$(BUILD)/.app
-	@$(MAKE) -C apps/$(APP) BASE=$(BASE) TOP=$(TOP) SHOW=$(SHOW) config
+	fi 
+	echo $(APP) >build/.app
 
-compile: compile-ioto compile-app
-
-compile-ioto: include/ioto-config.h
+compile:
 	@if [ ! -f $(PROJECT) ] ; then \
 		echo "The build configuration $(PROJECT) is not supported" ; exit 255 ; \
 	fi
-	@$(MAKE) -f $(PROJECT) OPTIMIZE=$(OPTIMIZE) ME_COM_$(LAPP)=1 PROFILE=default BUILD=$(BUILD) compile 
-	@echo '      [Info] Built the $(NAME) agent and library'
+	LAPP=$(shell echo $(APP) | tr a-z A-Z) ; \
+	$(MAKE) -f $(PROJECT) OPTIMIZE=$(OPTIMIZE) ME_COM_$${LAPP}=1 PROFILE=$(PROFILE) BUILD=$(BUILD) compile 
 
-compile-app:
-	$(MAKE) -C apps/$(APP) SHOW=$(SHOW) BASE=$(BASE) TOP=$(TOP) OPTIMIZE=$(OPTIMIZE) build
-
-#
-#	Create the ioto-config.h header from the app's ioto.json5
-#
-include/ioto-config.h: $(CONFIG)/ioto.json5
-	@echo '    [Create] ioto-config.h'
-	./bin/json --header services $(CONFIG)/ioto.json5 >include/ioto-config.h
-	rm -f $(BUILD)/obj/*.o
-
-certs: certs/test.crt
-
-certs/test.crt:
-	@echo '      [Info] Generate test certs'
-	bin/make-certs
-	mkdir -p $(BUILD)/bin
-	cp state/certs/roots.crt $(BUILD)/bin
+clean:
+	@echo '       [Run] $@'
+	@$(MAKE) -f $(PROJECT) TOP=$(TOP) APP=$(APP) PROFILE=$(PROFILE) $@
+	if [ -d samples/agent ] ; then make -C samples/agent clean ; fi
+	rm -f $(CONFIG)/db/*.jnl $(CONFIG)/db/*.db 
+	rm -f $(CONFIG)/db.json5 $(CONFIG)/display.json5 $(CONFIG)/local.json5
+	rm -f $(CONFIG)/signature.json5 $(CONFIG)/web.json5 $(CONFIG)/schema.json5
+	rm -fr projects/ioto-macosx-mine.xcodeproj
+	rm -fr ./bin/json
+	rm -fr ./state ./test/state ./test/*/state/certs
+	rm -fr test/.testme test/*/.testme test/*/certs test/scale/*/certs
+	rm -f .DS_Store */.DS_Store */*/.DS_Store */*/*/.DS_Store
+	rm -fr test/web/fuzz/crashes-archive/*
+	find . -name provision.json5 | xargs rm -f
+	find . -name ioto.key | xargs rm -f
+	find . -name ioto.crt | xargs rm -f
+	find . -name .testme | xargs rm -fr
+	find . -name '*K.txt' | xargs rm -f
 
 config-esp32:
 	@./bin/config-esp32 $(APP)
 
-clean clobber:
-	@echo '       [Run] $@'
-	@$(MAKE) -f $(PROJECT) TOP=$(TOP) APP=$(APP) $@
-	rm -f $(DB)/*.jnl $(DB)/*.db 
-	rm -f $(CONFIG)/db.json5 $(CONFIG)/display.json5 $(CONFIG)/local.json5
-	rm -f $(CONFIG)/signature.json5 $(CONFIG)/web.json5 $(CONFIG)/schema.json5
-	rm -fr ./build ./state
-	if [ -d apps/$(APP) ] ; then \
-		$(MAKE) -C apps/$(APP) SHOW=$(SHOW) BASE=$(BASE) TOP=$(TOP) clean ; \
-	fi
-
 install installBinary uninstall:
 	@echo '       [Run] $@'
-	@$(MAKE) -f $(PROJECT) TOP=$(TOP) APP=$(APP) $@
+	@$(MAKE) -f $(PROJECT) TOP=$(TOP) APP=$(APP) PROFILE=$(PROFILE) $@
 
 info:
-	@if [ "$(APP)" != 'blank' ] ; then \
-		echo "      [Info] Run via: \"make run\". Run \"ioto\" manually with \"$(BUILD)/bin\" in your path." ; \
-		echo "" ; \
-	fi
+	@VERSION=`json --default 1.2.3 version pak.json` ; \
+	echo "      [Info] Built Ioto $${VERSION} optimized for \"$(OPTIMIZE)\" with the \"$(APP)\" app"
+	echo "      [Info] Run via: \"sudo make run\". Run \"ioto\" manually with \"$(BUILD)/bin\" in your path."
 
+test:
+	# Check for test prerequisites
+	@./bin/prep-test.sh
+	tm test
+	
 run:
 	$(BUILD)/bin/ioto -v
 
@@ -149,14 +103,13 @@ path:
 #	Dump the local database contents. Note: the db may have data cached in memory for a little while
 #
 dump:
-	db --schema $(CONFIG)/schema.json5 $(DB)/device.db
+	db --schema $(CONFIG)/schema.json5 $(CONFIG)/db/device.db
 
 #
 #	Convenience targets for building various apps
 #
-auth eco demo blank unit: 
-	make APP=$@
-	@$(MAKE) TOP=$(TOP) APP=$@
+ai blank demo http unit: 
+	$(MAKE) TOP=$(TOP) APP=$@
 
 help:
 	@echo '' >&2
@@ -167,9 +120,10 @@ help:
 	@echo '' >&2
 	@echo 'Select from the following apps:' >&2
 	@echo '  ai 	Test invoking AI LLMs.' >&2
-	@echo '  auth	Test user login and authentication app.' >&2
 	@echo '  blank	Build without an app.' >&2
+	@echo '  blink	Blink the LED on ESP32.' >&2
 	@echo '  demo   Cloud-based Ioto demo sample app.' >&2
+	@echo '  http	Run just the web server.' >&2
 	@echo '' >&2
 	@echo 'To select your App, add APP=NAME:' >&2
 	@echo '' >&2
@@ -191,10 +145,8 @@ help:
 	@echo 'Use "SHOW=1 make" to show executed commands.' >&2
 	@echo '' >&2
 
-LOCAL_MAKEFILE := $(strip $(wildcard ./.local.mk))
-
-ifneq ($(LOCAL_MAKEFILE),)
-include $(LOCAL_MAKEFILE)
+ifneq ($(LOCAL),)
+include $(LOCAL)
 endif
 
 # vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4:
